name: Greeter

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  call-workflow:
    name: Call Workflow
    uses: nicklasfrahm-dev/.github/.github/workflows/documentation.yml@main
    secrets: inherit
    with:
      name: ${{ github.actor }}
