name: Release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  Release:
    name: Release
    uses: nicklasfrahm-dev/.github/.github/workflows/release-go-library.yml@main
    secrets: inherit
    permissions:
      checks: write
      contents: write
      pull-requests: write
      issues: write
