name: Release

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  documentation:
    uses: nicklasfrahm-dev/.github/.github/workflows/release-go-library.yml@main
    secrets: inherit
