name: Documentation

on:
  workflow_call:
    inputs:
      name:
        description: Person to greet
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -lah

      - name: Say hello
        run: echo Hello, ${{ inputs.name }}!
